### ISSUE TITLE
why don't load my "glb“ file？threejs and unity3d can load this file.

### ISSUE THREAD

**Issue by sui0312feng** [code4game/glTFForUE4#21]
[test.zip](https://github.com/code4game/glTFForUE4/files/5492777/test.zip)

**Comment by jixingcn** [comment]
Thanks a lot for the issue.
I just fix it a7026fc45b99e4f171ad48db5333dc44aae737aa.

**Reason:**

It was caused by the glb file that was mixed with some embedded data(base64).

**Solution:**

* Wait for next update (I will re-package the plugin as soon as possible.)
* Compile this plugin by yourself
* Don't export a glb file that is mixed with any embedded data
